config/routes.rb
Rails.application.routes.draw do

  get 'inquiry' => 'inquiry#index'
  post 'inquiry/confirm' => 'inquiry#confirm'
  post 'inquiry/thanks' => 'inquiry#thanks'

  root 'static_pages#home'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/portfolio', to: 'static_pages#portfolio', via: 'get'

end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :subject, :message

  # validates :name, presence: true
  # validates :email, presence: true
  # validates :message, presence: true

  validates :name, :presence => {:message => '名前を入力してください'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :format => {with: VALID_EMAIL_REGEX, :message => 'メールアドレスを入力してください'}
  validates :message, :presence => {:message => 'お問合せ内容を入力してください'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(params[:inquiry])
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/inquiry/confirm.html.erb
<% provide :title, "料金・お問合せ" %>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>格安で台湾の完全カスタマイズツアーを企画する台湾穴場旅行社 - 台南・高雄・台東でおすすめ観光スポット・見どころを紹介</title>

  <!-- Bootstrap -->
  <link href="../../assets/css/bootstrap.min.css" rel="stylesheet">
  <link href="../../assets/css/responsive-slider.css" rel="stylesheet">
  <link rel="stylesheet" href="../../assets/css/animate.css">
  <link rel="stylesheet" href="../../assets/css/font-awesome.min.css">
  <link rel="stylesheet" href="../../assets/css/magnific-popup.css">
  <link href="../../assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Arsha
    Theme URL: https://bootstrapmade.com/arsha-free-bootstrap-html-template-corporate/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.12&appId=182807229112317&autoLogAppEvents=1';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <header>
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <div class="navbar-brand">
                <a href="/" data-turbolinks="false"><img src="../../assets/top.png" alt="台湾穴場旅行"></a>
              </div>
            </div>
            <div class="menu">
              <ul class="nav nav-tabs" role="tablist">
                <li role="presentation"><a href="/" data-turbolinks="false">トップ</a></li>

                <!-- <li role="presentation"><a href="blog.html">blog</a></li> -->
                <li role="presentation"><a href="/portfolio">写真館</a></li>
                <li role="presentation" class="active"><a href="/inquiry" data-turbolinks="false">料金・問合せ</a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="recent">
        <button class="btn-primarys"><h3>料金・お問合せ</h3></button>
        <hr>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="recent">
          <button class="btn-primarys"><h3>お問合せ内容の確認</h3></button>
        </div>

        <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
          <div class="form-group">
            <%= f.hidden_field :name, :class => 'form-control' %>
            <%= simple_format(@inquiry.name) %>
          </div>
          <div class="form-group">
            <%= f.hidden_field :email, :class => 'form-control' %>
            <%= simple_format(@inquiry.email) %>
          </div>
          <div class="form-group">
            <%= f.hidden_field :subject, :class => 'form-control' %>
            <%= simple_format(@inquiry.subject) %>
          </div>
          <div class="form-group">
            <%= f.hidden_field :message, rows: 5, :class => 'form-control' %>
            <%= simple_format(@inquiry.message) %>
          </div>

          <%= f.submit "送信", :class => 'btn btn-default' %>
        <% end %>
      </div>



      <div class="col-lg-6">
        <div class="recent">
          <button class="btn-primarys"><h3>料金表&nbsp;(1日1人あたり)</h3></button>
        </div>
        <div class="contact-area">
          <div style="margin:0px;padding:0px;margin-top:11px;" align="center">
            <table width="98%" style="border-collapse: collapse;border:1px solid #000000;background-color:#FFFFFF;color:#000000;text-align:left;">
              <tbody>
                <tr><th style="border:1px solid #000000;background-color:#ADDE4A;color:#000000;text-align:center;">概要</th><th style="border:1px solid #000000;background-color:#ADDE4A;color:#000000;text-align:center;">2名様</th><th style="border:1px solid #000000;background-color:#ADDE4A;color:#000000;text-align:center;">3~6名様</th></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">基本ガイド料&nbsp;(ガイド宿泊費込)</td><td style="border:1px solid #000000;text-align:center;">2,000 台湾ドル</td><td style="border:1px solid #000000;text-align:center;">2,000 台湾ドル</td></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">レンタカー料&nbsp;(台南・高雄市内)</td><td style="border:1px solid #000000;text-align:center;">1,900 台湾ドル</td><td style="border:1px solid #000000;text-align:center;">2,000 台湾ドル</td></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">レンタカー料&nbsp;(台南・高雄郊外)</td><td style="border:1px solid #000000;text-align:center;">2,200 台湾ドル</td><td style="border:1px solid #000000;text-align:center;">2,000 台湾ドル</td></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">レンタカー料&nbsp;(台東)</td><td style="border:1px solid #000000;text-align:center;">3,000 台湾ドル</td><td style="border:1px solid #000000;text-align:center;">2,800 台湾ドル</td></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">レンタカー料&nbsp;(最南端)</td><td style="border:1px solid #000000;text-align:center;">お問合せください</td><td style="border:1px solid #000000;text-align:center;">お問合せください</td></tr>
              </tbody>
            </table>
          </div>
          <div style="margin-left:-12px;margin-top:14px;" align="left">
            <ol>
              <li style="margin-bottom:3px;">観光コースは自由に設定可能です(1日10時間以内)。</li>
              <li style="margin-bottom:3px;">レンタカー料には、車・運転手・駐車料金および高速道路料金が含まれています。</li>
              <li style="margin-bottom:3px;">2名様は一般の乗用車にて、3~6名様はワゴン車にてご案内いたします。</li>
              <li style="margin-bottom:3px;">施設入場料および食事・お土産などの費用はお客様各自のご負担となります。</li>
              <li style="margin-bottom:3px;">航空券およびお客様の宿泊費用は含まれておりません。</li>
              <li style="margin-bottom:3px;">小学生以下は無料です。</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <hr>
    </div>
  </div>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <div class="widget">
            <h5 class="widgetheading">会社概要</h5>
            <address>
            <strong>台湾穴場旅行社</strong><br>
            <strong>Taiwan Anaba Travel Co.</strong><br>
            台湾台南市永康区<br>
            代表: 謝詠麒<br>
            <br>
            <a class="fa fa-phone fa-1x"></a>&ensp;+886-919-141-550<br>
            <a class="fa fa-envelope fa-1x"></a>&ensp;info@taiwananabatravel.com
            </address>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="widget">
            <h5 class="widgetheading">サイトマップ</h5>
            <ul class="link-list">
              <li><a href="/" data-turbolinks="false">トップ</a></li>
              <li><a href="/portfolio">写真館</a></li>
              <li><a href="/inquiry" data-turbolinks="false">料金・問い合わせ</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="widget">
            <h5 class="widgetheading">お支払い方法</h5>
            <ul class="link-list">
              <li style="margin-bottom:5px;"><a>お支払いは全日程終了後、現金一括にて頂戴いたします。日本円または台湾ドルでのお支払いが可能です。</a></li>
              <li><a>ご宿泊の代理予約につきましては、一部ご予約金をいただく場合があります。</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="widget">
            <h5 class="widgetheading">Facebookページ</h5>
            <div class="fb-page" data-href="https://www.facebook.com/taiwananabatravelco/" data-tabs="timeline" data-height="155" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/taiwananabatravelco/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/taiwananabatravelco/">台湾穴場旅行</a></blockquote></div>
            <div class="clear">
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <hr>
      </div>
    </div>

    <div id="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <div class="copyright">
              <p>
                <a href="/" data-turbolinks="false">&copy; 台湾穴場旅行</a><span>, All right reserved.</span>
              </p>
              <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Arsha
                -->
                <small><a href="https://bootstrapmade.com/">Bootstrap Templates</a> by <a href="https://bootstrapmade.com/">BootstrapMade</a></small>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <ul class="social-network">
              <li><a class="joho" href="https://www.facebook.com/taiwananabatravelco/" data-placement="top" title="Facebook" target="_blank"><b>Facebookにて最新情報をお届け！ </b></a><a href="https://www.facebook.com/taiwananabatravelco/" data-placement="top" title="Facebook" target="_blank"><i class="fa fa-facebook-square fa-3x"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="../../assets/jquery.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="../../assets/bootstrap.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8HeI8o-c1NppZA-92oYlXakhDPYR7XMY"></script>
  <script src="../../assets/responsive-slider.js"></script>
  <script src="../../assets/wow.min.js"></script>
  <script src="../../assets/jquery.magnific-popup.js"></script>
  <script src="../../assets/functions.js"></script>
  <script src="../../assets/contactform.js"></script>
  <script>
    wow = new WOW({}).init();
  </script>

</body>
</html>

app/views/inquiry/index.html.erb
<% provide :title, "料金・お問合せ" %>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>格安で台湾の完全カスタマイズツアーを企画する台湾穴場旅行社 - 台南・高雄・台東でおすすめ観光スポット・見どころを紹介</title>

  <!-- Bootstrap -->
  <link href="assets/css/responsive-slider.css" rel="stylesheet">
  <link rel="stylesheet" href="../../assets/css/animate.css">
  <link rel="stylesheet" href="../../assets/css/font-awesome.min.css">
  <link rel="stylesheet" href="../../assets/css/magnific-popup.css">
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Arsha
    Theme URL: https://bootstrapmade.com/arsha-free-bootstrap-html-template-corporate/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.12&appId=182807229112317&autoLogAppEvents=1';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <header>
    <div class="container">
      <div class="row">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <div class="navbar-brand">
                <a href="/" data-turbolinks="false"><img src="assets/top.png" alt="台湾穴場旅行"></a>
              </div>
            </div>
            <div class="menu">
              <ul class="nav nav-tabs" role="tablist">
                <li role="presentation"><a href="/" data-turbolinks="false">トップ</a></li>

                <!-- <li role="presentation"><a href="blog.html">blog</a></li> -->
                <li role="presentation"><a href="/portfolio">写真館</a></li>
                <li role="presentation" class="active"><a href="/inquiry" data-turbolinks="false">料金・問合せ</a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="recent">
        <button class="btn-primarys"><h3>料金・お問合せ</h3></button>
        <hr>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="recent">
          <button class="btn-primarys"><h3>お問合せはこちら</h3></button>
        </div>

        <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>

          <% if @inquiry.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <strong>入力内容にエラーがあります</strong>
              <ul>
                <% @inquiry.errors.each do |attr, msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.text_field :name, :class => 'form-control', :placeholder => "お名前", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.email_field :email, :class => 'form-control',:placeholder => "メールアドレス", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.text_field :subject, :class => 'form-control', :placeholder => "件名", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.text_area :message, rows: 5, :class => 'form-control',:placeholder => "お問合せ内容", autofocus: true %>
          </div>

          <%= f.submit "確認", :class => 'btn btn-default' %>
        <% end %>
      </div>



      <div class="col-lg-6">
        <div class="recent">
          <button class="btn-primarys"><h3>料金表&nbsp;(1日1人あたり)</h3></button>
        </div>
        <div class="contact-area">
          <div style="margin:0px;padding:0px;margin-top:11px;" align="center">
            <table width="98%" style="border-collapse: collapse;border:1px solid #000000;background-color:#FFFFFF;color:#000000;text-align:left;">
              <tbody>
                <tr><th style="border:1px solid #000000;background-color:#ADDE4A;color:#000000;text-align:center;">概要</th><th style="border:1px solid #000000;background-color:#ADDE4A;color:#000000;text-align:center;">2名様</th><th style="border:1px solid #000000;background-color:#ADDE4A;color:#000000;text-align:center;">3~6名様</th></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">基本ガイド料&nbsp;(ガイド宿泊費込)</td><td style="border:1px solid #000000;text-align:center;">2,000 台湾ドル</td><td style="border:1px solid #000000;text-align:center;">2,000 台湾ドル</td></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">レンタカー料&nbsp;(台南・高雄市内)</td><td style="border:1px solid #000000;text-align:center;">1,900 台湾ドル</td><td style="border:1px solid #000000;text-align:center;">2,000 台湾ドル</td></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">レンタカー料&nbsp;(台南・高雄郊外)</td><td style="border:1px solid #000000;text-align:center;">2,200 台湾ドル</td><td style="border:1px solid #000000;text-align:center;">2,000 台湾ドル</td></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">レンタカー料&nbsp;(台東)</td><td style="border:1px solid #000000;text-align:center;">3,000 台湾ドル</td><td style="border:1px solid #000000;text-align:center;">2,800 台湾ドル</td></tr>
                <tr><td style="border:1px solid #000000;text-align:center;">レンタカー料&nbsp;(最南端)</td><td style="border:1px solid #000000;text-align:center;">お問合せください</td><td style="border:1px solid #000000;text-align:center;">お問合せください</td></tr>
              </tbody>
            </table>
          </div>
          <div style="margin-left:-12px;margin-top:14px;" align="left">
            <ol>
              <li style="margin-bottom:3px;">観光コースは自由に設定可能です(1日10時間以内)。</li>
              <li style="margin-bottom:3px;">レンタカー料には、車・運転手・駐車料金および高速道路料金が含まれています。</li>
              <li style="margin-bottom:3px;">2名様は一般の乗用車にて、3~6名様はワゴン車にてご案内いたします。</li>
              <li style="margin-bottom:3px;">施設入場料および食事・お土産などの費用はお客様各自のご負担となります。</li>
              <li style="margin-bottom:3px;">航空券およびお客様の宿泊費用は含まれておりません。</li>
              <li style="margin-bottom:3px;">小学生以下は無料です。</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <hr>
    </div>
  </div>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-3">
          <div class="widget">
            <h5 class="widgetheading">会社概要</h5>
            <address>
            <strong>台湾穴場旅行社</strong><br>
            <strong>Taiwan Anaba Travel Co.</strong><br>
            台湾台南市永康区<br>
            代表: 謝詠麒<br>
            <br>
            <a class="fa fa-phone fa-1x"></a>&ensp;+886-919-141-550<br>
            <a class="fa fa-envelope fa-1x"></a>&ensp;info@taiwananabatravel.com
            </address>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="widget">
            <h5 class="widgetheading">サイトマップ</h5>
            <ul class="link-list">
              <li><a href="/" data-turbolinks="false">トップ</a></li>
              <li><a href="/portfolio">写真館</a></li>
              <li><a href="/inquiry" data-turbolinks="false">料金・問い合わせ</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="widget">
            <h5 class="widgetheading">お支払い方法</h5>
            <ul class="link-list">
              <li style="margin-bottom:5px;"><a>お支払いは全日程終了後、現金一括にて頂戴いたします。日本円または台湾ドルでのお支払いが可能です。</a></li>
              <li><a>ご宿泊の代理予約につきましては、一部ご予約金をいただく場合があります。</a></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3">
          <div class="widget">
            <h5 class="widgetheading">Facebookページ</h5>
            <div class="fb-page" data-href="https://www.facebook.com/taiwananabatravelco/" data-tabs="timeline" data-height="155" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/taiwananabatravelco/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/taiwananabatravelco/">台湾穴場旅行</a></blockquote></div>
            <div class="clear">
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <hr>
      </div>
    </div>

    <div id="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <div class="copyright">
              <p>
                <a href="/" data-turbolinks="false">&copy; 台湾穴場旅行</a><span>, All right reserved.</span>
              </p>
              <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Arsha
                -->
                <small><a href="https://bootstrapmade.com/">Bootstrap Templates</a> by <a href="https://bootstrapmade.com/">BootstrapMade</a></small>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <ul class="social-network">
              <li><a class="joho" href="https://www.facebook.com/taiwananabatravelco/" data-placement="top" title="Facebook" target="_blank"><b>Facebookにて最新情報をお届け！ </b></a><a href="https://www.facebook.com/taiwananabatravelco/" data-placement="top" title="Facebook" target="_blank"><i class="fa fa-facebook-square fa-3x"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="../../assets/jquery.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="../../assets/bootstrap.min.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8HeI8o-c1NppZA-92oYlXakhDPYR7XMY"></script>
  <script src="../../assets/responsive-slider.js"></script>
  <script src="../../assets/wow.min.js"></script>
  <script src="../../assets/jquery.magnific-popup.js"></script>
  <script src="../../assets/functions.js"></script>
  <script src="../../assets/contactform.js"></script>
  <script>
    wow = new WOW({}).init();
  </script>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>台湾穴場旅行 | <%= yield :title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>